### ISSUE TITLE
大佬，有没有自动标注的快速入门教程啊

### ISSUE THREAD

**Issue by XhHello** [1844520476/Undergraduate-Graduation-Project#2]

**Comment by cleste-pome** [comment]
强烈安利Bilibili大学（误），跟李沐学AI、bryanyzhu、霹雳吧啦Wz、我是土堆、同济子豪兄、ShusenWang、Bubbliiiing、
Think 不 Clear、飞桨 PaddlePaddle、王晋东不在家等视频制作者的科普和教程都很不错！
ps.偷偷推销自己一波：论文所涉及的自动标注辅助工具内部模块使用到的相关函数实现、应用案例、扩充资料与理论基础等内容可以在我的个人博客https://blog.csdn.net/qq_44942172?type=blog中找到
